### ISSUE TITLE
Postprocessor loops .DateTime::__construct() Failed to parse time string (End of 2020

### ISSUE THREAD

**Issue by FzeroE** [NNTmux/newznab-tmux#1021]
**Describe the bug**
Postprocessor loops .
Im on branch master not sure if this is fixed in dev.

[2019-11-25 00:07:04] NNTmux.ERROR: DateTime::__construct(): Failed to parse time string (End of 2020) at position 0 (E): The timezone could not be found in the database {"exception":"[object] (Exception(code: 0): DateTime::__construct(): Failed to parse time string (End of 2020) at position 0 (E): The timezone could not be found in the database at /var/www/NNTmux/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:76)
[stacktrace]
#0 /var/www/NNTmux/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(76): DateTime->__construct('End of 2020', Object(Carbon\\CarbonTimeZone))
#1 /var/www/NNTmux/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(125): Carbon\\Carbon->__construct('End of 2020', NULL)
#2 /var/www/NNTmux/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(145): Carbon\\Carbon::rawParse('End of 2020', NULL)
#3 /var/www/NNTmux/Blacklight/Games.php(490): Carbon\\Carbon::parse('End of 2020')
#4 /var/www/NNTmux/Blacklight/Games.php(806): Blacklight\\Games->updateGamesInfo(Array)
#5 /var/www/NNTmux/Blacklight/processing/PostProcess.php(167): Blacklight\\Games->processGamesReleases()
#6 /var/www/NNTmux/misc/update/postprocess.php(92): Blacklight\\processing\\PostProcess->processGames()
#7 {main}

**Comment by DariusIII** [comment]
End of 2020 cannot be converted to datetime. Will try to fix.

**Comment by FzeroE** [comment]
you can close this i deleted the release.
