### ISSUE TITLE
 Trying to access array offset on value of type bool at Blacklight/Movie.php:687

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1104]
This seems to be introduced since PHP 7.4

```
REMOVED.ERROR: Trying to access array offset on value of type bool {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type bool at /var/www/REMOVED/Blacklight/Movie.php:687)
[stacktrace]
#0 /var/www/REMOVED/Blacklight/Movie.php(687): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/REMOVED/Blacklight/Movie.php(1122): Blacklight\\Movie->updateMovieInfo()
#2 /var/www/REMOVED/Blacklight/Movie.php(1277): Blacklight\\Movie->doMovieUpdate()
#3 /var/www/REMOVED/Blacklight/processing/PostProcess.php(186): Blacklight\\Movie->processMovieReleases()
#4 /var/www/REMOVED/misc/update/postprocess.php(114): Blacklight\\processing\\PostProcess->processMovies()
#5 {main}
"}
```

Offending line:

```php
            $mov['language'] = \is_array($imdb['language']) ? implode(', ', array_unique($omdb['language'])) : $omdb['language'];
```

**Comment by Fossil01** [comment]
Issue persists even after this commit. Same error, same line.

**Comment by Fossil01** [comment]
Still finding a lot of these in my logs but not seeing why.

**Comment by Fossil01** [comment]
Still getting this error.
