### ISSUE TITLE
Call to a member function update() on null at  Blacklight/NameFixer.php:1094

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1105]
```
[2020-04-27 11:05:48] REMOVED.ERROR: Call to a member function update() on null {"exception":"[object] (Error(code: 0): Call to a member function update() on null at /var/www/REMOVED/Blacklight/NameFixer.php:1094)
[stacktrace]
#0 /var/www/REMOVED/Blacklight/NameFixer.php(2525): Blacklight\\NameFixer->updateRelease()
#1 /var/www/REMOVED/Blacklight/NameFixer.php(1584): Blacklight\\NameFixer->preDbFileCheck()
#2 /var/www/REMOVED/Blacklight/NameFixer.php(323): Blacklight\\NameFixer->checkName()
#3 /var/www/REMOVED/misc/testing/Releases/fixReleaseNames.php(56): Blacklight\\NameFixer->fixNamesWithFiles()
#4 {main}
"}
```

Probably need to check for a value after line 1031 and do something if false/null.

**Comment by Fossil01** [comment]
Looks to be fixed, no mentions on logs anymore.
