### ISSUE TITLE
can't get ffmpeg to work.

### ISSUE THREAD

**Issue by jjaomni** [NNTmux/newznab-tmux#1165]
[2021-03-25 21:36:33] NNTmux.ERROR: Call to undefined method FFMpeg\Media\Audio::clip() {"exception":"[object] (Error(code: 0): Call to undefined method FFMpeg\\Media\\Audio::clip() at /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php:2021)

[stacktrace]
#0 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(2218): Blacklight\\processing\\post\\ProcessAdditional->_getVideo()
#1 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(1318): Blacklight\\processing\\post\\ProcessAdditional->_processVideoFile()
#2 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(735): Blacklight\\processing\\post\\ProcessAdditional->_processExtractedFiles()
#3 /var/www/NNTmux/Blacklight/processing/post/ProcessAdditional.php(549): Blacklight\\processing\\post\\ProcessAdditional->_processReleases()
#4 /var/www/NNTmux/Blacklight/processing/PostProcess.php(276): Blacklight\\processing\\post\\ProcessAdditional->start()
#5 /var/www/NNTmux/misc/update/postprocess.php(87): Blacklight\\processing\\PostProcess->processAdditional()
#6 {main}
"}

**Comment by jjaomni** [comment]
configuration issues
