### ISSUE TITLE
Zipped downloads broken on PHP 8.1

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1209]
This one is thrown when downloading multiple NZBs as a ZIP:

```
[2022-01-19 19:44:45] REMOVED.ERROR: Invalid or uninitialized Zip object {"userId":12345,"exception":"[object] (ValueError(code: 0): Invalid or uninitialized Zip object at /var/www/REMOVED/vendor/dariusiii/zipper/src/DariusIII/Zipper/Repositories/ZipRepository.php:159)
[stacktrace]
#0 /var/www/REMOVED/vendor/dariusiii/zipper/src/DariusIII/Zipper/Repositories/ZipRepository.php(159): ZipArchive->close()
#1 /var/www/REMOVED/vendor/dariusiii/zipper/src/DariusIII/Zipper/Zipper.php(68): DariusIII\\Zipper\\Repositories\\ZipRepository->close()
#2 /var/www/REMOVED/app/Http/Controllers/GetNzbController.php(113): DariusIII\\Zipper\\Zipper->__destruct()
```

**Comment by DariusIII** [comment]
I have enabled issues on the dariusiii/zipper repo, so please open this same issue there. Thank you!
