### ISSUE TITLE
Path cannot be empty (Utility.php:223)

### ISSUE THREAD

**Issue by Fossil01** [NNTmux/newznab-tmux#1214]
This happened after upgrading to PHP 8.1:

```
[2022-01-21 16:02:20] REMOVED.ERROR: Path cannot be empty {"exception":"[object] (ValueError(code: 0): Path cannot be empty at /var/www/REMOVED/Blacklight/utility/Utility.php:223)
[stacktrace]
#0 /var/www/REMOVED/Blacklight/utility/Utility.php(223): gzopen()
#1 /var/www/REMOVED/Blacklight/processing/post/ProcessAdditional.php(836): Blacklight\\utility\\Utility::unzipGzipFile()
#2 /var/www/REMOVED/Blacklight/processing/post/ProcessAdditional.php(724): Blacklight\\processing\\post\\ProcessAdditional->_getNZBContents()
#3 /var/www/REMOVED/Blacklight/processing/post/ProcessAdditional.php(574): Blacklight\\processing\\post\\ProcessAdditional->_processReleases()
#4 /var/www/REMOVED/Blacklight/processing/PostProcess.php(303): Blacklight\\processing\\post\\ProcessAdditional->start()
#5 /var/www/REMOVED/misc/update/postprocess.php(89): Blacklight\\processing\\PostProcess->processAdditional()
#6 {main}
"}
```

**Comment by Fossil01** [comment]
Maybe in ProcessAdditional.php `protected function _getNZBContents()` should return when $nzbPath is false? Now it just continues.

Like:

```php
    /**
     * Get list of contents inside a release's NZB file.
     *
     * @return bool
     *
     * @throws \Exception
     */
    protected function _getNZBContents(): bool
    {
        $nzbPath = $this->_nzb->NZBPath($this->_release->guid);
        if ($nzbPath === false) {
            $this->_echo('NZB not found for GUID: '.$this->_release->guid, 'warning');

            $this->_deleteRelease();

            return true;
        }

        $nzbContents = Utility::unzipGzipFile($nzbPath);
        if (! $nzbContents) {
            $this->_echo('NZB is empty or broken for GUID: '.$this->_release->guid, 'warning');

            $this->_deleteRelease();
        }

        // Get a list of files in the nzb.
        $this->_nzbContents = $this->_nzb->nzbFileList($nzbContents, ['no-file-key' => false, 'strip-count' => true]);
        if (\count($this->_nzbContents) === 0) {
            $this->_echo('NZB is potentially broken for GUID: '.$this->_release->guid, 'warning');

            $this->_deleteRelease();
        }
        // Sort keys.
        ksort($this->_nzbContents, SORT_NATURAL);

        return true;
    }
```
