### ISSUE TITLE
During class fetch: Uncaught Error: Class "Carbon\Carbon" not found in...

### ISSUE THREAD

**Issue by DrakeJones** [NNTmux/newznab-tmux#1267]
After be down for a few months (and running great), I just updated nntmux and Ubuntu 20.04.5 LTS packages and nntmux started throwing a carbon error (see below).  What did I mess up?  

using php 8.1 and a few pkgs auto-upgraded to 8.2.

```
PHP Fatal error:  During class fetch: Uncaught Error: Class "Carbon\Carbon" not found in /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Carbon.php:9
Stack trace:

#0 /var/www/NNTmux/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/NNTmux/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/DateFactory.php(215): method_exists()
#4 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Support\DateFactory->__call()
#5 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(550): Illuminate\Support\Facades\Facade::__callStatic()
#6 /var/www/NNTmux/vendor/laravel/telescope/src/IncomingEntry.php(77): now()
#7 /var/www/NNTmux/vendor/laravel/telescope/src/IncomingEntry.php(92): Laravel\Telescope\IncomingEntry->__construct()
#8 /var/www/NNTmux/vendor/laravel/telescope/src/Watchers/LogWatcher.php(37): Laravel\Telescope\IncomingEntry::make()
#9 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Laravel\Telescope\Watchers\LogWatcher->recordLog()
#10 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#11 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Log/Logger.php(245): Illuminate\Events\Dispatcher->dispatch()
#12 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Log/Logger.php(186): Illuminate\Log\Logger->fireLogEvent()
#13 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Log/Logger.php(106): Illuminate\Log\Logger->writeLog()
#14 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(126): Illuminate\Log\Logger->warning()
#15 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/helpers.php(418): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#16 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(122): with()
#17 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecationError()
#18 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#19 /var/www/NNTmux/vendor/composer/ClassLoader.php(571): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#20 /var/www/NNTmux/vendor/composer/ClassLoader.php(571): include('...')
#21 /var/www/NNTmux/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#22 /var/www/NNTmux/vendor/nesbot/carbon/src/Carbon/Carbon.php(510): Composer\Autoload\ClassLoader->loadClass()
#23 /var/www/NNTmux/vendor/composer/ClassLoader.php(571): include('...')
#24 /var/www/NNTmux/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#25 /var/www/NNTmux/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(49): Composer\Autoload\ClassLoader->loadClass()
#26 /var/www/NNTmux/vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php(29): Carbon\Laravel\ServiceProvider->updateLocale()
#27 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Carbon\Laravel\ServiceProvider->boot()
#28 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#29 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#30 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#31 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#32 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(928): Illuminate\Container\Container->call()
#33 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): Illuminate\Foundation\Application->bootProvider()
#34 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}()
#35 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(908): array_walk()
#36 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#37 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(239): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap()
#38 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith()
#39 /var/www/NNTmux/bootstrap/autoload.php(16): Illuminate\Foundation\Console\Kernel->bootstrap()
#40 /var/www/NNTmux/artisan(16): require('...')
#41 {main} in /var/www/NNTmux/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 510
**PHP Fatal error:  Uncaught Error: Class "Carbon\Carbon" not found in /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Carbon.php:9**
Stack trace:
#0 /var/www/NNTmux/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/NNTmux/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/DateFactory.php(215): method_exists()
#4 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Support\DateFactory->__call()
#5 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(550): Illuminate\Support\Facades\Facade::__callStatic()
#6 /var/www/NNTmux/vendor/laravel/telescope/src/IncomingEntry.php(77): now()
#7 /var/www/NNTmux/vendor/laravel/telescope/src/IncomingExceptionEntry.php(27): Laravel\Telescope\IncomingEntry->__construct()
#8 /var/www/NNTmux/vendor/laravel/telescope/src/IncomingEntry.php(92): Laravel\Telescope\IncomingExceptionEntry->__construct()
#9 /var/www/NNTmux/vendor/laravel/telescope/src/Watchers/ExceptionWatcher.php(45): Laravel\Telescope\IncomingEntry::make()
#10 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Laravel\Telescope\Watchers\ExceptionWatcher->recordException()
#11 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#12 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Log/Logger.php(245): Illuminate\Events\Dispatcher->dispatch()
#13 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Log/Logger.php(186): Illuminate\Log\Logger->fireLogEvent()
#14 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Log/Logger.php(155): Illuminate\Log\Logger->writeLog()
#15 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(702): Illuminate\Log\Logger->log()
#16 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(268): Illuminate\Log\LogManager->log()
#17 /var/www/NNTmux/app/Exceptions/Handler.php(54): Illuminate\Foundation\Exceptions\Handler->report()
#18 /var/www/NNTmux/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(46): App\Exceptions\Handler->report()
#19 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(189): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report()
#20 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#21 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#22 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#23 {main}
  **thrown in /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Support/Carbon.php on line 9**

```

**Comment by DrakeJones** [comment]
BAM! Just removed the 8.2 packages (8.1's were still installed) and nntmux fired right up.  Thanks, Fossil.  Much appreciated.
