### ISSUE TITLE
No Binaries being inserted if Compressed Headers is turned on

### ISSUE THREAD

**Issue by nightah** [NNTmux/newznab-tmux#135]
USP: Giganews

Steps to reproduce:
Turn on compressed headers

Within the tmux window with debug turned on I can see the following:
Received 11306KB from group (alt.binaries.hdtv.x264).
Process ID #4672 has completed.

There is no line to indicate inserting into sql.

Debug log shows the following:

> [23-Apr-2017 01:10:38 Australia/Melbourne] PHP Fatal error: Uncaught TypeError: Return value of nntmux\NNTP::_getXFeatureTextResponse() must be of the type string, array returned in /srv/http/NNTmux/nntmux/NNTP.php:1305
> Stack trace:
> #0 /srv/http/NNTmux/nntmux/NNTP.php(1237): nntmux\NNTP->_getXFeatureTextResponse()
> #1 /srv/http/NNTmux/nntmux/NNTP.php(450): nntmux\NNTP->_getTextResponse()
> #2 /srv/http/NNTmux/nntmux/Binaries.php(632): nntmux\NNTP->getXOVER('559224471-55947...')
> #3 /srv/http/NNTmux/nntmux/Binaries.php(507): nntmux\Binaries->scan(Array, 559224471, '559474470')
> #4 /srv/http/NNTmux/misc/update/update_binaries.php(29): nntmux\Binaries->updateGroup(Array, '2500000')
> #5 {main}
> thrown in /srv/http/NNTmux/nntmux/NNTP.php on line 1305

**Comment by nightah** [comment]
Fixed by https://github.com/NNTmux/newznab-tmux/commit/a1224f2d966718a10d456ff6b11c071a6eb17cbd

**Comment by nightah** [comment]
Still getting occasional errors, but binaries are being inserted now:

> [23-Apr-2017 08:40:21 Australia/Melbourne] PHP Fatal error:  Uncaught TypeError: Return value of nntmux\NNTP::_getXFeatureTextResponse() must be of the type array, object returned in /srv/http/NNTmux/nntmux/NNTP.php:1312
> Stack trace:
> #0 /srv/http/NNTmux/nntmux/NNTP.php(1237): nntmux\NNTP->_getXFeatureTextResponse()
> #1 /srv/http/NNTmux/nntmux/NNTP.php(450): nntmux\NNTP->_getTextResponse()
> #2 /srv/http/NNTmux/nntmux/Binaries.php(632): nntmux\NNTP->getXOVER('3448716343-3448...')
> #3 /srv/http/NNTmux/nntmux/Backfill.php(335): nntmux\Binaries->scan(Array, '3448716343', 3448716342, 'backfill')
> #4 /srv/http/NNTmux/nntmux/Backfill.php(179): nntmux\Backfill->backfillGroup(Array, 0, '1000000')
> #5 /srv/http/NNTmux/misc/update/backfill.php(24): nntmux\Backfill->backfillAllGroups('alt.binaries.hd...', '1000000')
> #6 {main}
>   thrown in /srv/http/NNTmux/nntmux/NNTP.php on line 1312
