### ISSUE TITLE
Repair parts grows when using mgr

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#637]
Been doing some testing, when using MGR option, I am getting lots of repairs appearing. In both normal and backfill.

When each has separate groups for tables, all okay even when doing backfills.

Any help appreciated.

**Comment by DariusIII** [comment]
You have probably added mgr posters whos releases cannot be completed.

**Comment by bert0901** [comment]
Even more weird, have almost double the amount of releases now when I don't use multigroup.

**Comment by DariusIII** [comment]
Maybe some of the releases from MGR are being created as separate releases?

**Comment by bert0901** [comment]
Nope, just done a side by side comparison. Also they seem more complete.

**Comment by DariusIII** [comment]
Can you, somehow, add some examples?

**Comment by bert0901** [comment]
One thing I have noticed also is that when doing individual groups I get "sleeping" now and again. When using MGR, it just automatically goes to repair tables. Not sure if this is related.

Never see "sleeping for x seconds" when using the MGR.

**Comment by bert0901** [comment]
Will setup a mgr version later today and will do a group comparison. I will use the same newsserver as well so all will be the same.

**Comment by bert0901** [comment]
Trying to do the comparison.

Getting lots of errors when using mgr :

Think its to do with part repairs handling

[2018-07-08 16:48:52] NNTmux.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`nzbplus`.`multigroup_binaries`, CONSTRAINT `FK_MGR_Collections` FOREIGN KEY (`collections_id`) REFERENCES `multigroup_collections` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: INSERT INTO multigroup_binaries (id, partsize, currentparts) VALUES (2856,30937702,39),(2858,104978666,133),(2860,104980463,133),(2863,104978450,133),(2864,104979222,133),(2866,104981146,133),(2867,104981331,133),(2869,104979877,133),(2871,104983470,133),(2873,104978935,133),(19009,0,0),(19011,104981402,133),(19013,104972695,133),(19014,104971613,133),(19016,104973253,133),(19018,104972815,133),(19019,104968303,133),(19021,104972019,133),(19022,104970606,133),(19024,104970776,133),(19025,104972985,133),(19027,104975933,133),(19028,104971874,133),(19030,104974432,133),(19032,104972805,133),(19034,104970622,133),(19035,104971370,133),(19037,104974808,133),(19039,104977118,133),(19041,104970330,133),(19042,104970242,133),(19044,104967492,133),(19045,104968204,133),(19047,104968991,133),(19048,104968854,133),(19050,104970828,133),(19051,104969554,133),(19053,104972436,133),(19054,104971151,133),(19056,104974376,133),(19057,104975396,133),(19059,85251145,108),(19060,793402,1),(19062,0,0),(19063,12692764,16),(19065,3173113,4),(19066,1586465,2),(19067,5790172,8),(19069,24575151,31),(19070,49466496,63),(19072,64959730,82),(19074,0,0),(19075,104968653,133),(19076,104959380,133),(19078,105000396,133),(19079,104977933,133),(19081,105023011,133),(19082,104968862,133),(19084,104976490,133),(19085,104964007,133),(19087,105074681,133),(19089,105097447,133),(19090,104964691,133),(19092,105017478,133),(19093,104965367,133),(19095,105178406,133),(19096,105004376,133),(19098,105067687,133),(19099,105052346,133),(19101,105048514,133),(19102,104996015,133),(19104,105032974,133),(19105,105105034,133),(19107,105090350,133),(19108,104994745,133),(19110,105000035,133),(19111,105029374,133),(19113,6343932,8),(19114,793236,1),(19116,0,0),(19117,6346080,8),(19119,3173049,4),(19120,1586384,2),(19122,12692987,16),(19123,24472358,31),(19125,49344166,63),(19126,34541928,44),(19129,0,0),(19130,104975392,133),(19132,104973127,133),(19134,104973998,133),(19135,104968828,133),(19137,104977755,133),(19138,104997906,133),(19140,104976534,133),(19141,104973175,133),(19143,104971908,133),(19144,104984193,133),(19146,104970862,133),(19148,105038228,133),(19149,104969581,133),(19151,104974080,133),(19153,104973909,133),(19154,104973082,133),(19156,104974761,133),(19157,104976218,133),(19159,104973207,133),(19160,104979202,133),(19162,104981251,133),(19163,104982650,133),(19165,104984835,133),(19166,105086203,133),(19168,105029353,133),(19169,105052557,133),(19171,104972769,133),(19172,104969500,133),(19174,104973646,133),(19176,104975214,133),(19177,105028922,133),(19179,104970070,133),(19180,104971928,133),(19181,104972802,133),(19183,104972725,133),(19184,105037442,133),(19186,105084944,133),(19188,105009797,133),(19189,104993999,133),(19191,104973445,133),(19192,105035081,133),(19194,104999178,133),(19195,104987202,133),(2726,103430025,131),(2725,7143716,9) ON DUPLICATE KEY UPDATE partsize = VALUES(partsize) + partsize, currentparts = VALUES(currentparts) + currentparts) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`nzbplus`.`multigroup_binaries`, CONSTRAINT `FK_MGR_Collections` FOREIGN KEY (`collections_id`) REFERENCES `multigroup_collections` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: INSERT INTO multigroup_binaries (id, partsize, currentparts) VALUES (2856,30937702,39),(2858,104978666,133),(2860,104980463,133),(2863,104978450,133),(2864,104979222,133),(2866,104981146,133),(2867,104981331,133),(2869,104979877,133),(2871,104983470,133),(2873,104978935,133),(19009,0,0),(19011,104981402,133),(19013,104972695,133),(19014,104971613,133),(19016,104973253,133),(19018,104972815,133),(19019,104968303,133),(19021,104972019,133),(19022,104970606,133),(19024,104970776,133),(19025,104972985,133),(19027,104975933,133),(19028,104971874,133),(19030,104974432,133),(19032,104972805,133),(19034,104970622,133),(19035,104971370,133),(19037,104974808,133),(19039,104977118,133),(19041,104970330,133),(19042,104970242,133),(19044,104967492,133),(19045,104968204,133),(19047,104968991,133),(19048,104968854,133),(19050,104970828,133),(19051,104969554,133),(19053,104972436,133),(19054,104971151,133),(19056,104974376,133),(19057,104975396,133),(19059,85251145,108),(19060,793402,1),(19062,0,0),(19063,12692764,16),(19065,3173113,4),(19066,1586465,2),(19067,5790172,8),(19069,24575151,31),(19070,49466496,63),(19072,64959730,82),(19074,0,0),(19075,104968653,133),(19076,104959380,133),(19078,105000396,133),(19079,104977933,133),(19081,105023011,133),(19082,104968862,133),(19084,104976490,133),(19085,104964007,133),(19087,105074681,133),(19089,105097447,133),(19090,104964691,133),(19092,105017478,133),(19093,104965367,133),(19095,105178406,133),(19096,105004376,133),(19098,105067687,133),(19099,105052346,133),(19101,105048514,133),(19102,104996015,133),(19104,105032974,133),(19105,105105034,133),(19107,105090350,133),(19108,104994745,133),(19110,105000035,133),(19111,105029374,133),(19113,6343932,8),(19114,793236,1),(19116,0,0),(19117,6346080,8),(19119,3173049,4),(19120,1586384,2),(19122,12692987,16),(19123,24472358,31),(19125,49344166,63),(19126,34541928,44),(19129,0,0),(19130,104975392,133),(19132,104973127,133),(19134,104973998,133),(19135,104968828,133),(19137,104977755,133),(19138,104997906,133),(19140,104976534,133),(19141,104973175,133),(19143,104971908,133),(19144,104984193,133),(19146,104970862,133),(19148,105038228,133),(19149,104969581,133),(19151,104974080,133),(19153,104973909,133),(19154,104973082,133),(19156,104974761,133),(19157,104976218,133),(19159,104973207,133),(19160,104979202,133),(19162,104981251,133),(19163,104982650,133),(19165,104984835,133),(19166,105086203,133),(19168,105029353,133),(19169,105052557,133),(19171,104972769,133),(19172,104969500,133),(19174,104973646,133),(19176,104975214,133),(19177,105028922,133),(19179,104970070,133),(19180,104971928,133),(19181,104972802,133),(19183,104972725,133),(19184,105037442,133),(19186,105084944,133),(19188,105009797,133),(19189,104993999,133),(19191,104973445,133),(19192,105035081,133),(19194,104999178,133),(19195,104987202,133),(2726,103430025,131),(2725,7143716,9) ON DUPLICATE KEY UPDATE partsize = VALUES(partsize) + partsize, currentparts = VALUES(currentparts) + currentparts) at /var/www/nzbplus/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`nzbplus`.`multigroup_binaries`, CONSTRAINT `FK_MGR_Collections` FOREIGN KEY (`collections_id`) REFERENCES `multigroup_collections` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) at /var/www/nzbplus/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:143, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`nzbplus`.`multigroup_binaries`, CONSTRAINT `FK_MGR_Collections` FOREIGN KEY (`collections_id`) REFERENCES `multigroup_collections` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) at /var/www/nzbplus/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141)
[stacktrace]
#0 /var/www/nzbplus/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('INSERT INTO mul...', Array, Object(Closure))
#1 /var/www/nzbplus/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('INSERT INTO mul...', Array, Object(Closure))
#2 /var/www/nzbplus/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('INSERT INTO mul...', Array)
#3 /var/www/nzbplus/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\\Database\\Connection->insert('INSERT INTO mul...')
#4 /var/www/nzbplus/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Database\\DatabaseManager->__call('insert', Array)
#5 /var/www/nzbplus/Blacklight/Binaries.php(971): Illuminate\\Support\\Facades\\Facade::__callStatic('insert', Array)
#6 /var/www/nzbplus/Blacklight/Binaries.php(742): Blacklight\\Binaries->storeHeaders(Array, true)
#7 /var/www/nzbplus/misc/update/multiprocessing/.do_not_run/switch.php(78): Blacklight\\Binaries->scan(Object(App\\Models\\Group), '1467384228', '1467404227', 'update')
#8 {main}
"}

**Comment by DariusIII** [comment]
This error actualy means that binaries are being inserted where referencing collection does not exist, aka. has been deleted from multigroup_collections table.

**Comment by bert0901** [comment]
It only happens in multigroup and not separate tables, just wasn't sure if it was an issue or not.
